### ISSUE TITLE
[1.14] Support BungeeCord with forge

### ISSUE THREAD

**Issue by 1a2s3d4f1** [OKTW-Network/FabricProxy#1]
BungeeCord
(forge_support: true)
Minecraft 1.14 fabric server

client error:
`lost connection: Internal Exception: net.minecraft.class_151: Non [a-z0-9/._-] character in path of location: legacy:fml|hs`

**Comment by james58899** [comment]
Can't reproduce, try update bungee to latest version

![](https://user-images.githubusercontent.com/5798637/58379977-717c9200-7fdd-11e9-9939-bd1ebc182711.png)

**Comment by 1a2s3d4f1** [comment]
bungeecord is latest 
1.14 （no 1.14.1）fabric client can not join to fabric server

**Comment by 1a2s3d4f1** [comment]
sorry , This is broken by fabric api 
https://github.com/FabricMC/fabric/issues/181
https://github.com/FabricMC/fabric/issues/140
