### ISSUE TITLE
Unable to connect via Velocity

### ISSUE THREAD

**Issue by Hellhium** [OKTW-Network/FabricProxy#20]
I'm completely unable to connect the server via velocity ( 1.1.2 ), connecting directly to the server works
This issue only affects 1.4.5 

Currently running with: online-mode=true
fabric-api-0.28.4+1.16.jar
FabricProxy-1.4.5.jar

```
BungeeCord = false
BungeeCordWorkaround = false
Velocity = true
allowBypassProxy = true
secret = "REDACTED"
```

**Comment by james58899** [comment]
Try update velocity to 1.1.3
Maybe related to this issue: https://github.com/VelocityPowered/Velocity/issues/407

**Comment by Hellhium** [comment]
Upgrading to Velocity 1.1.3 has fixed the issue, thanks a lot
