### ISSUE TITLE
FabricProxy 1.4.5 breaks connecting to a fabric server through Velocity

### ISSUE THREAD

**Issue by Justsnoopy30** [OKTW-Network/FabricProxy#21]
FabricProxy 1.4.5 breaks connecting to a fabric server through Velocity. Downgrading to 1.4.2 fixes the issue, and I am running the latest version of fabric api and Velocity 1.1.3.

**Comment by james58899** [comment]
Any error logs?

**Comment by SirOMGitsYOU** [comment]
I'm having this issue currently, there are no error logs generated. Sadly unlike @Justsnoopy30, I'm not able to fix this by simply downgrading FP and Velocity. 

Edit: While I was writing this it just generated the first error I've seen.

Here is a log for all 3 instances (client, velocity & papermc lobby server) 
https://gist.githubusercontent.com/SirOMGitsYOU/11ee0b3c8791570562d33d094dd662b0/raw/28ce9b84a584fed2e3303d7262b11c03724ce531/Error%2520Logs

**Comment by james58899** [comment]
@SirOMGitsYOU PaperMC? FabricProxy is a fabric mod not bukkit plugin.
PaperMC no need this mod, it support velocity natively.

**Comment by SirOMGitsYOU** [comment]
> @SirOMGitsYOU PaperMC? FabricProxy is a fabric mod not bukkit plugin.
> PaperMC no need this mod, it support velocity natively.

I'm using Fabric Modpack to connect to my network using Velocity, my lobby server is running Paper which doesn't let me connect natively with fabric mod loader.

**Comment by SirOMGitsYOU** [comment]
Basically what I'm trying to say is I'm using it for it's intended purpose and it's not working lol

**Comment by james58899** [comment]
> Basically what I'm trying to say is I'm using it for it's intended purpose and it's not working lol

This mod only add support for forwarding player information form proxy.
Modded client should not be able connect to vanilla server.

**Comment by SirOMGitsYOU** [comment]
> > Basically what I'm trying to say is I'm using it for it's intended purpose and it's not working lol
> 
> This mod only add support for forwarding player information form proxy.
> Modded client should not be able connect to vanilla server.

I see okay is there no way to make it so the client would be able to join vanilla server? Or is that impossible as it works with forge so i thought it would work the same

**Comment by SirOMGitsYOU** [comment]
> > Basically what I'm trying to say is I'm using it for it's intended purpose and it's not working lol
> 
> This mod only add support for forwarding player information form proxy.
> Modded client should not be able connect to vanilla server.

I have just tried velocity connecting directly to a fabric server and get the same result. 

Error log: https://gist.githubusercontent.com/SirOMGitsYOU/01ad7b6b6b628bd5e345ca4abc7ed26e/raw/241a901ccae0774c88de727f5d2f689b44121572/Velocity%2520error

This is all that minecraft shows;
https://i.imgur.com/OmIafMP.png

**Comment by gniftygnome** [comment]
Same as the OP; I just switched from Waterfall to Velocity and had to downgrade FabricProxy.  The logs are very quiet when it fails.  The client waits for some time at "Joining World..." then goes to the disconnected screen.  With downgraded FabricProxy the connection completes in about 3 or 4 seconds.

Velocity says:
[13:41:12 INFO]: [connected player] GniftyGnome (/199.58.103.135:46510) has connected
[13:41:12 INFO]: [server connection] GniftyGnome -> creative has connected
[13:41:41 ERROR]: [connected player] GniftyGnome (/199.58.103.135:46510): read timed out
[13:41:41 INFO]: [connected player] GniftyGnome (/199.58.103.135:46510) has disconnected
[13:41:41 INFO]: [server connection] GniftyGnome -> creative has disconnected

And the server (1.16.5 with a bunch of Fabric mods) says:
[13:41:41] [Server thread/INFO]: com.mojang.authlib.GameProfile@66462779[id=0d8d919f-1aee-4051-b2fa-9b4704f3bd50,name=GniftyGnome,properties={textures=[com.mojang.authlib.properties.Property@73fdf7b9]},legacy=false] (/199.58.103.135:42110) lost connection: Disconnected

(That's my own user so I don't care enough to bother anonymizing it.)

**Comment by james58899** [comment]
I still can't reproduce this issue.

@gniftygnome Could you provide full logs from server and proxy?

**Comment by gniftygnome** [comment]
[server.txt](https://github.com/OKTW-Network/FabricProxy/files/5864034/server.txt)
[velocity.txt](https://github.com/OKTW-Network/FabricProxy/files/5864036/velocity.txt)

OK; ignore references to 'survival' and 'lobby'; at this point in the maintenance I had not yet gotten to those.  Later in the velocity log where you stop seeing timeouts on 'creative' it's because I downgraded FabricProxy to 1.4.2.

**Comment by gniftygnome** [comment]
I've been poking around at this some more on a test instance and what I'm seeing is it takes a good number of mods on the server side to reproduce.  (What mods the client has doesn't seem to matter.)  I haven't found any one mod that is required, but all the combinations I've tried so far of just a few mods have worked.

For example, removing all the Terraformers mods plus Wild World and Xaero's World Map is enough to resolve the issue, but on the other hand, using just those same mods (plus Fabric Proxy, Crossstitch, and Fabric API) also works fine.

**Comment by james58899** [comment]
I'm not very sure issue is resolved.
This issue is cause by mixin order, FabricProxy mixin need load after Fabric-API.

**Comment by gniftygnome** [comment]
> I'm not very sure issue is resolved.

I know that feeling...  FWIW the new version is working for me.
