### ISSUE TITLE
QUERY_START event not called when connecting via Bungeecord

### ISSUE THREAD

**Issue by zedwick** [OKTW-Network/FabricProxy#22]
**Describe the bug**
Fabric API does not fire the ServerLoginConnectionEvents.QUERY_START event with FabricProxy installed and `BungeeCordWorkaround` set to `true`.

**Expected behavior**
ServerLoginConnectionEvents.QUERY_START should fire when logging in to the server, this is used by LuckPerms (Relevant issue: https://github.com/lucko/LuckPerms/issues/2855)

**FabricProxy.toml**
Provide you config (without secret):
```
BungeeCord = true
BungeeCordWorkaround = true
Velocity = false
allowBypassProxy = false

```

**Versions**
Minecraft version: 1.16.5
FabricProxy version: 1.4.6
Fabric API version:0.29.4+1.16
BungeeCord version: git:BungeeCord-Bootstrap:1.16-R0.4-SNAPSHOT:281aece:1538

**Additional context**
Setting `BungeeCordWorkaround = false` allows the event to fire, though I can't successfully connect with it disabled.

**Comment by james58899** [comment]
Not FabricProxy bug. see https://github.com/OKTW-Network/FabricProxy/issues/16#issuecomment-751494731

**Comment by zedwick** [comment]
Ah. Are there open issues tracking this problem with BungeeCord and Fabric API?

**Comment by james58899** [comment]
> Ah. Are there open issues tracking this problem with BungeeCord and Fabric API?

https://github.com/SpigotMC/BungeeCord/pull/3012

**Comment by zedwick** [comment]
Just to let you know, this has been resolved in BungeeCord: https://github.com/SpigotMC/BungeeCord/commit/a7c6edeb638f0a2ba4fb051f2b0be5a6e226c955
