### ISSUE TITLE
Console Error and Disconnect

### ISSUE THREAD

**Issue by LucidAPs** [OKTW-Network/FabricProxy#23]
FabricProxy version 1.4.6
Waterfall 1.16.5 #394

Fabric Settings:
BungeeCord = true
BungeeCordWorkaround = true
Velocity = false
allowBypassProxy = false
secret = ""

Console Error:
https://nekobin.com/bavorucufe

**Comment by james58899** [comment]
This is not issue of FabricProxy.
Please report to waterfall or fabric api.

I recommend switch to velocity, It have better mod support

**Comment by james58899** [comment]
Maybe disabled forge support in waterfall config will help.
fabric doesn't need it.
