### ISSUE TITLE
[1.16.4]ops can't join the server 

### ISSUE THREAD

**Issue by ghost** [OKTW-Network/FabricProxy#24]
**Describe the bug**
When you appoint yourself as OP, the server cannot enter.

**Expected behavior**
When you appoint yourself as OP, you can enter the server normally.

**FabricProxy.toml**
Provide you config (without secret):
```
BungeeCord = true
BungeeCordWorkaround = true
Velocity = false
allowBypassProxy = true
```

**Versions**
Minecraft version:1.16.4
FabricProxy version:FabricProxy-1.4.6.jar
Fabric API version:fabric-api-0.30.0+1.16.jar
Velocity version:
BungeeCord version:waterfall-1.16-393.jar（I tested it at bungeecord, too.）

**Server log**
Provide any related logs on the server side:
```
Paste log here
```

**Proxy log**
Provide any related logs on the proxy side:
```
Paste log here
```

**Additional context**

**Comment by james58899** [comment]
BungeeCord log?

Maybe some mod using custom Brigadier argument types, BungeeCord not support it.
You can change to Velocity and install CrossStitch mod.
