### ISSUE TITLE
Could you please accept the 1.17.1 Pull Request? [Not an Issue]

### ISSUE THREAD

**Issue by MrR341-GER** [OKTW-Network/FabricProxy#29]
Please accept the 1.17.1 pull request #28 .
My Servers are all down...

**Comment by james58899** [comment]
You can download PR version from CI.
https://github.com/OKTW-Network/FabricProxy/pull/28/checks

**Comment by MrR341-GER** [comment]
Where from What? Sry.. I cant find anything to download...

**Comment by MrR341-GER** [comment]
nvm.. found it
