### ISSUE TITLE
Question about BungeeCord 1.19

### ISSUE THREAD

**Issue by voruti** [OKTW-Network/FabricProxy#34]
Since FabricProxy is deprecated and not available for Minecraft 1.19, do I now have to switch to Velocity (and use FabricProxyLite) when I want to upgrade my Fabric-Server to Minecraft 1.19?
I can barely find any plugins to use with Velocity for the functionality I currently have on BungeeCord!

**Comment by voruti** [comment]
Implemented it by myself: https://github.com/voruti/FabricProxy-Legacy

**Comment by cjtganzon** [comment]
you are a life saver!
